#!/usr/bin/python

from collections import defaultdict
import json
import sqlite3

import click


# From the Anki schema
revlog_cols = 'id cid usn ease ivl lastIvl factor time type'.split()

# Columns in `cards` in the Anki schema:
#   id nid did ord mod usn type queue due ivl factor reps lapses left odue odid flags data
# did is deck id, ord goes with nid; leave those unmodified
# odue, odid are when in a filtered deck, flags, data unused; forbid those
# type...left are learning status; copy those
# copy mod, set usn
cards_copy_cols = 'mod type queue due ivl factor reps lapses left'.split()


from_mid = 1455531004306  # "Kanji - Heisig order (new edition)"
to_mid = 1458405833105  # "Remembering the Kanji writings"


def sql_list(items):
    '''NB does not escape!'''
    return ', '.join(items)


def sql_plist(items):
    '''NB does not escape!'''
    return '(%s)' % (sql_list(items),)


def query_one_value(cur, *args):
    return list(cur.execute(*args))[0][0]


def count_stuff(cur):
    notecounts = defaultdict(int,
        {mid: c for mid, c in
         cur.execute('select mid, count(*) from notes where mid in (?, ?) group by mid',
                     (from_mid, to_mid))})
    cardcounts = defaultdict(int,
        {mid: c for mid, c in
         cur.execute('''select mid, count(*) from cards, notes
                        where nid = notes.id and mid in (?, ?) group by mid''',
                     (from_mid, to_mid))})
    revlogcounts = defaultdict(int,
        {mid: c for mid, c in
         cur.execute('''select mid, count(*) from revlog, cards, notes
                        where cid = cards.id and nid = notes.id
                          and mid in (?, ?) group by mid''',
                     (from_mid, to_mid))})
    return notecounts, cardcounts, revlogcounts


@click.command()
@click.argument('collection')
def main(collection):
    '''Migrate history from one RTK-correlated deck to a better one.

    Your collection is assumed to have a deck with the structure of
    this one: https://ankiweb.net/shared/info/1862058740 and you want
    to switch to this one: https://ankiweb.net/shared/info/1999412794
    preserving all study history.

    This script will (a) identify which new-model cards correspond to
    which old-model cards by RTK frame number; (b) synthesize
    learn/review history records ("revlogs" in the Anki schema) for
    the new-model cards just like those for the corresponding old
    cards; (c) update the study metadata (due date, ease, etc.) on the
    new-model cards likewise.
    '''

    cxn = sqlite3.connect(collection)
    cur = cxn.cursor()

    models = json.loads(list(cur.execute('select models from col'))[0][0])
    from_model = models.get(str(from_mid))
    to_model = models.get(str(to_mid))
    if from_model is None:
        raise click.ClickException('Note model %d (the "from" model) not present!'
                                   % (from_mid,))
    if to_model is None:
        raise click.ClickException('Note model %d (the "to" model) not present!'
                                   % (to_mid,))
    if 'rtk index' not in from_model['flds'][-1]['name'].lower():
        raise click.ClickException('''\
Old note model has field %r where RTK frame number expected.
This script is simple-minded and just looks in the one place, but
does try to corroborate by checking the field name, and that name
doesn't sound right.
        ''' % (from_model['flds'][-1]['name']))
    if (to_model['sortf'] != 0
        or to_model['flds'][0]['name'] != 'frame'):
        raise click.ClickException('''\
New note model not as expected.
This script is simple-minded; generalize it as needed.''')
    
    notecounts, cardcounts, revlogcounts = count_stuff(cur)
    print '# Old-model notes/cards/revlogs: %d %d %d' % (
        notecounts[from_mid], cardcounts[from_mid], revlogcounts[from_mid])
    print '# New-model notes/cards/revlogs: %d %d %d' % (
        notecounts[to_mid], cardcounts[to_mid], revlogcounts[to_mid])
    
    if revlogcounts[to_mid] != 0:
        raise click.ClickException('''\
History for new model already exists.

This script isn't designed for this case.  Should it wipe out the
existing history, or somehow complement it?  Think it through
and edit the script accordingly before using.''')

    if list(cur.execute('''
        select 1 from cards, notes where nid = notes.id and mid in (?, ?)
                                     and (odue != 0 or odid != 0) limit 1''',
                        (from_mid, to_mid))):
        raise click.ClickException('''\
One or more cards on old or new model is in a filtered deck.
This case seems complicated and this script is too simple for it.
Return them to their original decks.''')
    if list(cur.execute('''
        select 1 from cards, notes where nid = notes.id and mid in (?, ?)
                                     and (cards.flags != 0 or cards.data != '') limit 1''',
                        (from_mid, to_mid))):
        raise click.ClickException('''\
Some card has a nonempty `flags` or `data`!
These are supposedly unused fields; unsure how to handle them.''')

    oldnid_by_frame = {}
    frame_by_oldnid = {}
    for nid, flds in cur.execute('select id, flds from notes where mid = ?',
                                 (from_mid,)):
        _, frame_id_str = flds.rsplit('\x1f', 1)
        if not frame_id_str:
            continue
        frame_id = int(frame_id_str)
        oldnid_by_frame[frame_id] = nid
        frame_by_oldnid[nid] = frame_id
    print '# Old notes with a frame ID: %d' % (len(oldnid_by_frame),)
    print '# Old cards with any study history: %d' % (query_one_value(cur, '''
        select count(*) from cards, notes
        where nid = notes.id and mid = ? and cards.type != 0''', (from_mid,)),)


    newcid_by_frame = {}
    for cid, sfld in cur.execute('''
        select cards.id, sfld from cards, notes
        where nid = notes.id and mid = ?''',
                                 (to_mid,)):
        newcid_by_frame[sfld] = cid
    print '# New cards: %d' % (len(newcid_by_frame),)
    if len(newcid_by_frame) != cardcounts[to_mid]:
        raise click.ClickException('Mismatch ^')

    skipped_revlogs = []
    new_revlogs = []
    for row in cur.execute('''
            select nid, ''' + sql_list('revlog.' + c for c in revlog_cols) + '''
            from revlog, cards, notes
            where cid = cards.id and nid = notes.id and mid = ?''',
                           (from_mid,)):
        nid, revid, cid, usn = row[:4]
        if nid not in frame_by_oldnid:
            skipped_revlogs.append(row)
            continue
        newcid = newcid_by_frame[frame_by_oldnid[nid]]
        # The `id` value in revlog is the timestamp of the learn/review,
        # in epoch-ms.  We preserve the time information, just adding 1ms
        # because as the primary key it needs to be distinct.
        new_revlogs.append((revid+1, newcid, -1) + row[4:])
    print '# History records on frameless cards: %d' % (len(skipped_revlogs),)
    print 'Creating new history records (%d of them)...' % (len(new_revlogs),)
    cur.executemany('insert into revlog %s values %s'
                    % (sql_plist(revlog_cols), sql_plist(['?'] * len(revlog_cols))),
                    new_revlogs)

    skipped_cards = []
    cards_updates = []
    cards_read_cols = ['id', 'nid'] + cards_copy_cols
    cards_write_cols = ['usn'] + cards_copy_cols
    for row in cur.execute('''
            select ''' + sql_list('cards.' + c for c in cards_read_cols) + '''
            from cards, notes
            where nid = notes.id and mid = ?''',
                           (from_mid,)):
        cid, nid = row[:2]
        if nid not in frame_by_oldnid:
            skipped_cards.append(row)
            continue
        if row[3] == 0: # type
            # if never seen, no history; don't make noise bumping mod/usn
            continue
        newcid = newcid_by_frame[frame_by_oldnid[nid]]
        cards_updates.append((-1,) + row[2:] + (newcid,))
    print '# Frameless cards: %d' % (len(skipped_cards),)
    print 'Updating cards (%d of them)...' % (len(cards_updates),)
    cur.executemany('update cards set %s = %s where id = ?'
                    % (sql_plist(cards_write_cols),
                       sql_plist(['?'] * len(cards_write_cols))),
                    cards_updates)
    
    notecounts, cardcounts, revlogcounts = count_stuff(cur)
    print '# Old-model notes/cards/revlogs: %d %d %d' % (
        notecounts[from_mid], cardcounts[from_mid], revlogcounts[from_mid])
    print '# New-model notes/cards/revlogs: %d %d %d' % (
        notecounts[to_mid], cardcounts[to_mid], revlogcounts[to_mid])

    print 'Updating collection modtime...'
    cur.execute('''update col set mod = (strftime('%s', 'now') + 1) * 1000''')

    cxn.commit()
    print 'Done!'


if __name__ == '__main__':
    main()



"""

new card:
nid->mid = NEW
nid->sfld -> (n2.flds like X'251f' || n1.sfld)


perl:
make table old_nid frame
then sqlite:
with
 cardmap as
  (select newc.id as new_cid, oldc.* from cards as oldc, oldmap, notes as newn, cards as newc
   where oldc.nid = oldmap.nid and oldmap.frame = newn.sfld and newn.id = newc.nid)
update cards set type, queue, due, ivl, factor, reps, lapses, left, odue, odid, flags, data
 = type, queue, due, ivl, factor, reps, lapses, left, odue, odid, flags, data
 where id = cardmap.new_cid
"""
